username_textbox_xpath = '//input[@name="username"]'
password_textbox_xpath = '//input[@name="password"]'
login_button_xpath = '//button[@class="euiButton euiButton--primary euiButton--fill"]'
dashboard_label_xpath = '//h1[text()="Welcome home"]'
devtools_div_input_xpath = '//div[@class="ace_content"]'
devtools_textarea_input_xpath = '//textarea[@class="ace_text-input"]'
query_execute_button_xpath = '//button[@class="euiLink css-pqycxy-euiLink-success"]'
output_statusCode_xpath = '//span[@class="euiBadge__text"]'
output_textarea_xpath = '//div[@class="conApp__output ace_editor ace-tm"]'
